import fs from "node:fs";
import assert from "node:assert/strict";

const source = fs.readFileSync("src/index.js", "utf8");
for (const name of ["routeMessage","isProjectRequest","sanitizeProjectName","validateAgentPlan","buildAgentPlan","shouldFallbackToChat","summarizeAgentStatus","safeCalculate","basicPythonValidation","executeAgentPlan"]) {
  assert.match(source, new RegExp("function " + name + "\\s*\\("), "missing function: " + name);
}
assert.match(source, /export const __test = \{/);
assert.match(source, /generate_project/);
assert.match(source, /package_generated_project/);
assert.match(source, /search_web/);
assert.match(source, /get_current_weather/);
assert.match(source, /generate_or_repair_code/);
assert.match(source, /async function generateCodingResponse/);
assert.match(source, /if \(step\.tool === "coding"\)/);
assert.match(source, /basicPythonValidation\(code\)/);
assert.match(source, /temperature: 0\.1/);
assert.match(source, /120000/);
assert.match(source, /retry/);

assert.match(source, /\/api\/health/);
assert.match(source, /version:\s*"4\.8"/);
assert.match(source, /\/api\/chat/);
assert.match(source, /\/api\/project/);
assert.match(source, /\/api\/project\/ci/);
assert.match(source, /NEYQORA_CI_RESULT/);
assert.match(source, /api.github.com\/repos\/perdeson359-design\/neyqora\/issues/);
assert.match(source, /\/api\/search/);
assert.match(source, /\/api\/memory/);
assert.match(source, /memory-panel/);
assert.match(source, /loadMemories/);
assert.match(source, /method:"DELETE"/);
assert.match(source, /all=1/);
assert.match(source, /deletedCount/);
assert.match(source, /clear-memories/);
assert.match(source, /Kayıtlı tüm hafıza silinsin mi/);
assert.match(source, /loadMemories\(\);/);
assert.match(source, /DELETE FROM memories WHERE user_id = \? AND id = \?/);
assert.match(source, /SELECT id, content, created_at FROM memories/);
assert.match(source, /Response\.json\(\{ ok: true/);
assert.match(source, /memory:\s*!!env\.DB/);
assert.match(source, /toolResults: agentResults/);
assert.match(source, /agentStatus/);
assert.match(source, /executeToolStep/);
assert.match(source, /isBlockedFetchUrl/);
assert.match(source, /contentLength > 256000/);
assert.match(source, /message.length > 8000/);
assert.match(source, /historyChars > 20000/);
assert.match(source, /async function generateCodingResponse/);
assert.match(source, /tool: "coding"/);
assert.match(source, /ok: !!reply && validation.ok/);
assert.match(source, /function verifyOwnerSession/);
assert.match(source, /\/api\/auth\/owner/);
assert.match(source, /OWNER_AUTH_TOKEN/);
assert.match(source, /unlimited: true/);
assert.match(source, /isOwner \? "owner" : requestedUserId/);
assert.match(source, /function shouldRemember/);
assert.match(source, /function extractMemory/);
assert.match(source, /function normalizeMemory/);
assert.match(source, /function memoryCategory/);
assert.match(source, /\/api\/files\/analyze/);
assert.match(source, /function getFileExtension/);
assert.match(source, /function isAnalyzableFile/);
assert.match(source, /function normalizeFileText/);
assert.match(source, /En fazla 5 dosya/);
assert.match(source, /4_000_000/);
assert.match(source, /Dosyaları Analiz Et/);
assert.match(source, /file-input/);
assert.match(source, /LIMIT -1 OFFSET 50/);
assert.match(source, /Kullanıcının adı:%/);
assert.match(source, /function isNameQuestion/);
assert.match(source, /function forgetRequest/);
assert.match(source, /adımı\\|ismimi/);
assert.match(source, /Kullanıcının adı/);
assert.match(source, /type: detail \? "text" : "latest"/);
assert.match(source, /type: "all"/);
assert.match(source, /şu bilgiyi/);
assert.match(source, /quoted/);
assert.match(source, /type: "name"/);
assert.match(source, /memoryCleared: true/);
assert.match(source, /DELETE FROM memories WHERE user_id = \?/);
assert.match(source, /function sanitizeProjectFiles/);
assert.match(source, /function validateGeneratedProject/);
assert.match(source, /path\.includes\(".."\)/);
assert.match(source, /eval|exec/);
assert.match(source, /max 8 files|En fazla 8 dosya/);
assert.match(source, /path\.startsWith\("\/"\)|path\.includes\("\\\\"\)|unsafe/i);
assert.match(source, /files\.length > 8/);
assert.match(source, /validateGeneratedProject/);
assert.match(source, /templateFiles \|\| await generateProjectFiles/);

assert.match(source, /if \(intent === "coding"\) \{/);
assert.match(source, /codingReply = result\?\.reply/);
assert.match(source, /codingValidation = result\?\.validation/);
assert.match(source, /validation: codingValidation/);

console.log("NEYQORA core contract tests: PASS");
